biolab/orange-canvas-core

orangecanvas/application/widgettoolbox.py

Due to change in ToolGridButton's size policy in 7059c5c5bb3fd37dee19624cb56b944ed66b62cd the grid no longer constrains the size in the vertical direction, causing the button grid to fill available space

[FIX] widgettoolbox: Fix layout size hint for the widget tool box

---

orangecanvas/application/canvasmain.py
orangecanvas/gui/toolgrid.py

Fixes gh-2
The change in 7059c5c5bb3fd37dee19624cb56b944ed66b62cd
broke icon size resolve w.r.t client supplied icon sizes
(it could never shrink below PM_LargeIconSize).

[FIX] toolgrid: Fix default (style) icon size

---

orangecanvas/help/provider.py
orangecanvas/help/tests/test_provider.py
orangecanvas/utils/__init__.py
orangecanvas/utils/tests/test_utils.py

*help.provider:HtmlIndexProvider*
Try to parse the html meta charset declaration when parsing the help index. If successful use the declared charset.
Fixes gh-9

[FIX] Help index encoding detection

---

orangecanvas/application/canvastooldock.py
orangecanvas/document/interactions.py
orangecanvas/document/quickmenu.py
orangecanvas/gui/tooltree.py
orangecanvas/gui/utils.py
orangecanvas/styles/orange.qss

I think the quick menu has potential to be prettier.
v1

[ENH] Quick Menu Redesign

---

orangecanvas/application/welcomedialog.py
orangecanvas/document/quickmenu.py
orangecanvas/gui/toolbox.py
orangecanvas/styles/orange.qss

Fix some size hinting and styling/drawing issues
The background for icons in the side toolbox would *bleed* from out the bounding borders on 2x retina displays (particularly noticeable in dark styles)
Before 
After
The default width size hinting for 'category' buttons in quick menu was to low, which was compensated for in the style orange.qss style sheet. When running without the style sheet applied the buttons are not wide enough.

[FIX] Fix styling and size hinting issues

---

orangecanvas/document/editlinksdialog.py
orangecanvas/registry/base.py
orangecanvas/registry/description.py
orangecanvas/registry/qt.py
orangecanvas/registry/tests/test_base.py
orangecanvas/scheme/link.py
orangecanvas/scheme/node.py
orangecanvas/scheme/scheme.py
orangecanvas/scheme/signalmanager.py
orangecanvas/scheme/tests/test_links.py
orangecanvas/utils/__init__.py

Allow the specification of union types by generalizing the the single type spec in the Input/OutputSignal to a tuple of types.
Ref: https://github.com/biolab/orange3/pull/3545#issuecomment-456373380
A strict connection type checks if all the source types are subtypes of the sink types.
A dynamic connection type checks if at least one of the sink types is a subtype of one of the source types.

[ENH] Allow specification of union types in input/output meta defintions

---

orangecanvas/scheme/tests/__init__.py
orangecanvas/scheme/tests/test_widgetmanager.py
orangecanvas/scheme/widgetmanager.py

Add a pair or shortcuts for raising the ancestors (<kbd>ctrl + shift + left</kbd>) and descendants (<kbd>ctrl + shift + right</kbd>).
When there are more then one immediate ancestor/descendants all are raised and the focus restored to the last to have had it.

[ENH] widgetmanager: Add a raise ancestors/descendents to widget's actions

---

orangecanvas/application/canvasmain.py
orangecanvas/application/settings.py
orangecanvas/config.py
orangecanvas/document/quickmenu.py
orangecanvas/gui/lineedit.py
orangecanvas/gui/tooltree.py
orangecanvas/gui/utils.py
orangecanvas/styles/orange.qss

Categories in the QuickMenu are hidden by default.
As per discussion in #16, buttons were made lighter. They were also made smaller, such that the menu does not get too large when many addons are installed.
Additionally, the search icon shadow was refactored, a background color change was added.

quickmenu: Add preference setting to display categories, lighten and smallen tab buttons

---

orangecanvas/application/canvasmain.py
orangecanvas/document/interactions.py
orangecanvas/document/schemeedit.py
orangecanvas/document/usagestatistics.py

The following information is newly submitted with each statistics session:
- node removal actions
- link addition/removal actions
Additionally, all actions are now collected in one list (allowing temporal
information to be inferred).
Still, in most cases, the workflow will not be reconstructible from the gathered statistics. Widgets are not associated with an ID, meaning it is not possible to distinguish between two widgets of the same type.

Extend usage statistics tracking with more actions

---

orangecanvas/gui/toolbox.py

Before this commit, the toolbox sizehint was computed as if the scrollbar was always present, adding some empty space to the right side of the toolbox, should the scrollbar be set to transient (on Mac, this is done by changing the `Show scroll bars` setting in General System Preferences).

toolbox: Set sizehint in accordance with scrollbar transientness

---

orangecanvas/canvas/items/nodeitem.py

A couple of months ago, the larger target area functionality of the node anchor was (likely accidentally) removed. This has been reinstated, and the width of the area doubled.

Make target area of widget extend anchor larger

---

orangecanvas/application/addons.py
orangecanvas/canvas/items/annotationitem.py
orangecanvas/help/manager.py
orangecanvas/utils/markup.py
orangecanvas/utils/shtools.py
orangecanvas/utils/tests/test_markup.py
orangecanvas/utils/tests/test_shtools.py

Refactor and cleanup the addons dialog.
* Remove unused code.
* Move some utilities from the addons module to utils.
* Extract and reuse the text markup rendering from annotationitem to render the add-on description text (adding support for markdown (commonmark variant only)

Addons Dialog Refactor/Cleanup

---

orangecanvas/utils/__init__.py

Since gh-11 the I/O tooltips in the toolbox contain 'Union[...]' for all items (even when the I/O has a single has a single type member).
Simplify the type string for a single union member.

Prettify the tool tip when the type union has a single member

---

orangecanvas/document/schemeedit.py
orangecanvas/document/tests/test_schemeedit.py

Copy/Paste as implemented in  gh-25 does not work between multiple editor windows.
Implement Copy/Paste via the system clipboard.

schemeedit: Copy/paste via the system clipboard

---

orangecanvas/document/quickmenu.py

1. On macOS quick menu does not have a size grip and so cannot be resized like on other platforms.
Fixed by forcing non zero size on the size grip.
2. The size only persists within a single editor window.
Fixed by storing the size on menu hide event and restoring on first show.

Quick menu macOS size grip

---

orangecanvas/help/provider.py

Use a single shared QNetworkAccessManager instance for fetching help indices.

help/provider: Use a single QNetworkAccessManager instance

---

orangecanvas/application/canvasmain.py
orangecanvas/config.py

The workflow dialog is used to set the title and description of the workflow. I believe this feature is superfluous to most Orange users.
The title is referenced in the save dialog, but this will be changed in https://github.com/biolab/orange-canvas-core/pull/43.
The description is really only used for example workflows.
The dialog is still accessible with the `i` button in the bottom-left corner, `File -> Workflow Info` and the `CMD+I` keyboard shortcut.

Hide workflow info dialog by default

---

orangecanvas/document/interactions.py

Sometimes I grab an anchor with the intention of adding a new widget via the quick menu, but change my mind before I let go of the mouse button. Instinctively I press ESC, with the expectation that the new link interaction will be canceled.
The base class for interactions (`UserInteraction`) defines a `self.cancelOnEsc` boolean, which is set False by default. From what I can tell, no interaction uses this option.
Should it be enabled by default, some interactions such as resize arrow, resize text, break – the object is not restored to its previous state, and undo doesn't work properly.

Cancel new link action on ESC

---

orangecanvas/application/canvasmain.py

- Recognize when workflow is not yet saved, changing the dialog text
- Reference filename instead of workflow title
When the workflow is not yet saved, and the user tries to close the window, the text is now one line long. I feel as if the window should automatically be smaller vertically, but couldn't figure out why it's not.

canvasmain: Make unsaved changes dialog more dynamic

---

orangecanvas/canvas/items/controlpoints.py

Control point edit fails on a double click.
Steps:
1) Add a Text/Arrow annotation to the workflow.
2) Select the annotation item, to start edit its geometry
3) Double click one of the displayed the control point and move it. The point is disconnected from the main item.
Keep track of the active control point on double click.

[FIX] controlpoints: Fix point selection/tracking on double click

---

orangecanvas/scheme/tests/test_widgetmanager.py
orangecanvas/scheme/widgetmanager.py

If adding nodes to workflow when the widget manager is in OnDemand creation policy, and then switching to Normal, the nodes that were added are not scheduled for widget creation as the new policy would suggest.
Add nodes to init queue to complete when/if transitioned back to Normal policy.

[FIX] widgetmanager: Add nodes to init queue in OnDemand policy

---

docs/source/orangecanvas/scheme.events.rst
docs/source/orangecanvas/scheme.node.rst
docs/source/orangecanvas/scheme.rst
docs/source/orangecanvas/scheme.scheme.rst
orangecanvas/canvas/items/linkitem.py
orangecanvas/registry/description.py
orangecanvas/scheme/__init__.py
orangecanvas/scheme/events.py
orangecanvas/scheme/link.py
orangecanvas/scheme/node.py
orangecanvas/scheme/signalmanager.py
orangecanvas/scheme/tests/test_signalmanager.py
orangecanvas/scheme/tests/test_widgetmanager.py
orangecanvas/scheme/widgetmanager.py
orangecanvas/utils/__init__.py

`SignalManager.is_blocking` is insufficient (the current and only async execution support).
While in this state the widget will not receive any signal inputs, neither will all its dependents. It would be beneficial to split the state into two:
* Prevent signal delivery to this node.
* Prevent signal delivery to its dependents (or even delivery of only specific outputs).
* `SignalManager.is_ready` indicates if a node can receive new input signals.
* `SignalManager.is_invalidated` indicates all outputs should be considered invalidated.
* `SignalManager.invalidate` invalidates a single output channel.

SignalManager: Add support for output invalidation

---

orangecanvas/document/schemeedit.py

The 'Duplicate selected' action can raise an error when no nodes are selected:
```
---------------------------- ValueError Exception -----------------------------
File "/Users/aleserjavec/workspace/orange-canvas/orangecanvas/document/schemeedit.py", line 1846, in __duplicateSelected
pos = nodes_top_left(nodedups)
File "/Users/aleserjavec/workspace/orange-canvas/orangecanvas/document/schemeedit.py", line 2382, in nodes_top_left
min(n.position[0] for n in nodes),
ValueError: min() arg is an empty sequence
-------------------------------------------------------------------------------
```
Do nothing no nodes are selected.

[FIX] Fix an error on duplicate action with empty selection

---

orangecanvas/scheme/signalmanager.py
orangecanvas/scheme/tests/test_signalmanager.py

`SignalManager.process_next`(explicit) differs from `SignalManager.__process_next`(event queue scheduled).
* Extract code from `__process_next` into a helper function and call it from both implementations.

[FIX] SignalManager: `process_next` differes from normal event queue sceduled 

---

orangecanvas/document/schemeedit.py

As `item_at()` only returns the top item when the `buttons` parameter is specified, links cannot be interacted with if a widget anchor is hovering over them. This became more prominent when the widget anchors' clickable area was enlarged.
This PR passes right-click and double-click events through to the link.

Enable link interactions when link is below anchor

---

orangecanvas/application/addons.py

The add-on dialog does quit the application when instructed to if there are multiple open editor windows.
Steps:
* Open two workfloes
* Open Add-ons
* Select something to (un)install
* Click Ok
* Click Ok again in the restart prompt dialog.
Close all windows not just the parent ones.

[FIX] addons: On prompt to restart, close all windows

---

orangecanvas/application/canvasmain.py
orangecanvas/document/interactions.py
orangecanvas/document/schemeedit.py
orangecanvas/document/tests/test_usagestatistics.py
orangecanvas/document/usagestatistics.py

Statistics now tracks actions and events separately. A session is constructed of several actions, each of which has a type and a corresponding list of events. Concatenating all events of a session allows reconstruction of the workflow.
**Tracked events**
NodeAdd
NodeRemove
LinkAdd
LinkRemove
**Tracked actions**
Unclassified
ToolboxClick
ToolboxDrag
QuickMenu
ExtendFromSink
ExtendFromSource
InsertDrag
InsertMenu
Undo
Redo
Duplicate 
Load 
The current implementation of deleting items on canvas (`deleteSelected()`) makes it difficult to track as one action. It's fine if it's left unclassified for now. Otherwise, all canvas interactions should be accounted for. Should anything be forgotten, it will be tagged as unclassified.
**TODO**
- Add `more info` link to:

UsageStatistics: Reconstructible workflows

---

orangecanvas/canvas/scene.py

The workflow previews in Recent/Examples workflows have a non-constant width border around them (depends on the overall scene size).
Do not draw view box rect outline in svg preview generation.

[FIX] Preview: Do not render view box border

---

orangecanvas/application/addons.py

Since gh-26 project descriptions in rst without declared 'description-content-type' render as plain text only.
Fixes gh-62
Try parsing as rst in case 'description-content-type' is not defined.

addons: Restore default rst description parsing

---

orangecanvas/document/usagestatistics.py

By including a launch count parameter in statistics sessions, it's possible to reliably distinguish new and old Orange users.
1. In `Orange/version.py`, set versions to `3.24.0` and `release = True`,
2. Open Orange, play around in canvas,
3. Close Orange,
4. Open Orange (statistics are sent upon start),
Statistics are stored in `/srv` on the service server.

usagestatistics: Include launch count in statistics session

---

orangecanvas/application/canvasmain.py

In Orange3, a `NotificationOverlay` is instantiated in its `MainWindow` subclass, where it is also connected to a `NotificationServer` instance.

canvasmain: Remove redundant NotificationOverlay instantiation

---

orangecanvas/canvas/items/linkitem.py
orangecanvas/canvas/scene.py
orangecanvas/document/schemeedit.py

A double-click on a widget is caught by a NodeItem's `mouseDoubleClickEvent()`, mapped to the CanvasScene's `node_item_activated` signal, emitting a call to `__onNodeActivate` in the SchemeEditWidget.
Double-clicking a link was handled in SchemeEditWidget's `eventFilter()`, installed on the CanvasScene, which takes precedence over CanvasScene's and its children's events (i.e., NodeItem activate).
This PR implements an `activated` signal in LinkItem. The double-click now propagates according to the z-value of QGraphicsWidgets. In other words, NodeItem takes the event because it's above the LinkItem in the scene.

[FIX] Double-click NodeItem when above a LinkItem

---

orangecanvas/canvas/items/nodeitem.py
orangecanvas/document/schemeedit.py

Since gh-28 mouse click on a node would not work if a another node's anchor was behind it.
* Use `buttons` parameter to query the NodeAnchorItem
* Disable all mouse buttons on LinkAnchorIndicator

Fix node selection when the node is in front of a link anchor

---

orangecanvas/canvas/items/nodeitem.py

When extending a widget (dragging its anchor), the color of the anchor should remain darker, but its hover shadow should disappear.
I appreciate the nodeitem drawing code is getting quite complex. If this were more readable implemented another way, please suggest such an implementation.

nodeitem: Hide shadow upon anchor drag

---

orangecanvas/document/interactions.py
orangecanvas/document/tests/test_schemeedit.py

Add text/arrow annotations should support 'cancel on escape key'
Enable and implement cancel operations on 'Add Text/Arrow annotation' interaction handlers.

[ENH] Add Annotations:  Cancel on escape key

---

orangecanvas/application/tests/test_mainwindow.py
orangecanvas/gui/test.py
orangecanvas/gui/tests/test_stackedwidget.py
orangecanvas/scheme/widgetmanager.py
orangecanvas/utils/tests/test_resources.py

Tests fail randomly with PyQt5 5.14.*
Ref: https://github.com/biolab/orange-canvas-core/pull/79#issuecomment-583663808
* Preserve QApplication between tests when running tests with PyQt5 >= 5.14
* Fix some resulting errors in tests due to changed test setup/teardown

Fixes for testing with PyQt 5.14

---

orangecanvas/application/application.py

Ref https://github.com/biolab/orange3/issues/4488
When PyQt5 is installed from wheel file into a path with non-latin1
characters, the platform plugins cannot be loaded and the application
cannot start.
Try to detect non valid plugins path and attempt to set explicit search path with `QCoreApplication.addLibraryPath`

Try to fix Qt plugins search path

---

orangecanvas/application/canvasmain.py
orangecanvas/application/tests/test_mainwindow.py
orangecanvas/document/commands.py
orangecanvas/document/interactions.py
orangecanvas/document/schemeedit.py
orangecanvas/scheme/annotations.py
orangecanvas/scheme/link.py
orangecanvas/scheme/node.py
orangecanvas/utils/pickle.py
setup.py

(note: crashed changes for scratch workflows are loaded on startup like this with https://github.com/biolab/orange3/pull/4392)
As outlined in #44, this PR saves the undo stack since its last clean state, and the diff of 'clean node' properties since last clean state, any time a command is pushed to the undo stack.
This is saved to `./.workflow.ows.swp.p` if it's a saved workflow, or `configdir/scratch-crashes/scratch.swp.p.0` if it's a scratch workflow, where 0 is incremented in the case of several crashed scratch workflows.
I've not yet extensively tested the pickling and restoring of node properties; an issue would arise if a property is unpicklable. There are ways to combat this, e.g., ignoring the property in `uncleanProperties()`, as are contexts.
**TODO**

[ENH] Crash recovery

---

orangecanvas/application/canvasmain.py
orangecanvas/application/settings.py
orangecanvas/application/tests/test_mainwindow.py
orangecanvas/config.py
orangecanvas/utils/pickle.py

#97 
- canvasmain: Bugfix for loading swp of open workflow
- config: Add option for not loading/saving scratch workflows

Crash recovery bugfix, scratch workflow config option

---

orangecanvas/application/addons.py
orangecanvas/application/tests/test_addons.py

Archives containing already installed add-ons did not work. Now, whatever is dropped is installed. These changes allow installing arbitrary versions (old, or perhaps unreleased) through drag-and-drop onto the dialog.
Another change: the installed versions are now displayed even if installed version is greater than pypi version.

add-on dialog: fix drag-and-drop support for already installed add-ons

---

orangecanvas/scheme/signalmanager.py
orangecanvas/scheme/tests/test_signalmanager.py

compress_signals should compress `None` signals when `None` is last in sequence.
Compress 'None' signals when 'None' is last in sequence

[FIX] signalmanager: Fix compress_signals

---

orangecanvas/application/canvasmain.py

#100 introduced a dynamic warning message that did not work.

[FIX] canvasmain: Fix addon warning

---

orangecanvas/application/addons.py

Fixes https://github.com/biolab/orange3/issues/4844
With @markotoplak, we discussed that conda and pip installer should have similar behavior. Pip's behavior while installing packages is to upgrade/downgrade packages only if needed while conda upgrade them while installing new packages. Conda's behavior can cause problems in cases similar to the one that just happened whit scikit-learn. The package gets a new release which is incompatible with Orange. Orange will still work since it has an older version of a package in the installer, but when someone installs the add-on packages are upgraded and Orange stops working.
This flag should solve those problems. But do we want that? 
This flag was added in the conda version 4.6.0, we are currently building installers with Miniconda 4.7.12, so it …

Conda installer: add --satisfied-skip-solve

---

orangecanvas/scheme/readwrite.py

Setting this to avoid potential future problems. Before, pickle protocol 3 was used for Python <= 3.7 and 4 for Python 3.8. Protocol v4 is compatible with Python>=3.4, which is also the minimum supported python for orange-canvas-core.

Scheme: explicitly set pickle protocol to v4

---

setup.py

`markup.render_markdown` only works with commonmark>=0.8.1
Ref: gh-111
Specify a lower version bound for `commonmark` in dependencies.

setup.py: Specify minimum bound for commonmark version

---

orangecanvas/utils/settings.py

*Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working.*

Import MutableMapping from typing, not collections

---

orangecanvas/document/quickmenu.py

Typing 'heatmap' in the quick menu will now find the 'Heat Map' widget.

quickmenu: Match titles with no spaces queries

---

orangecanvas/application/canvasmain.py

The welcome screen shouldn't be shown if a crashed swp file was loaded. This change lets orange3 know when not to show it.

canvasmain: Return boolean swp loaded

---

orangecanvas/canvas/scene.py

For me, rectangle selection always resulted in a laggy shadow animation for nodes and links.
This PR disables animations on any interactions handler being set in scene, namely rectangle select, and annotation interactions. Of course, a more elegant solution would be to find the underlying problem and fix that.

scene: Disable animations on interactions handler (rectangle select)

---

orangecanvas/application/canvasmain.py

This is unnecessary, the swp file is cleared when the workflow is saved/closed. With the current behavior, if the swp is restored (and deleted), and Orange crashes again (likely to happen if it's crashed at this point before), the swp is lost.

canvasmain: Don't delete swp on swp load

---

orangecanvas/application/application.py

PyQt5 is weird, this needs to be set for it to show shortcuts in menus (that aren't in the menubar) by default. 
I did this so it shows up when you right-click a widget on canvas, but it'll probably affect menus elsewhere too.

application: Show shortcuts in context menus on PyQt5.13 and up

---

docs/source/orangecanvas/scheme.events.rst
orangecanvas/document/commands.py
orangecanvas/document/tests/test_schemeedit.py
orangecanvas/scheme/events.py
orangecanvas/scheme/scheme.py
orangecanvas/scheme/tests/test_scheme.py
orangecanvas/scheme/tests/test_widgetmanager.py
orangecanvas/scheme/widgetmanager.py

Undo/redo of node, link and annotations removal does not preserve their order in the underlying model.
I.e. redo of a remove action always places the respective element at last position.
* Extend Scheme class with insert_{node,link,annotation} methods
* Make Remove{Node,Link,Annotation}Command insert the element at the appropriate place.

[FIX] Undo/redo does not preserve order

---

orangecanvas/application/canvasmain.py
orangecanvas/utils/pickle.py

Fixes a bug introduced by #131. 
Loading a swp and making a change resulted in another swp file being created. This change correctly associates the canvas instance with the loaded swp file.

Fix swp duplication upon loading swp file

---

.travis.yml
orangecanvas/document/commands.py
orangecanvas/document/schemeedit.py
orangecanvas/document/tests/test_schemeedit.py
orangecanvas/scheme/scheme.py

After saving a window group (View -> Window Groups -> Save Window Group) any modification to the workflow logs an error:
```
ERROR:orangecanvas.application.canvasmain:Could not write swp file '/Users/aleserjavec/Library/Application Support/Orange/3.27.0.dev/scratch-crashes/scratch.swp.p.0'.
File "/Users/aleserjavec/workspace/orange-canvas/orangecanvas/application/canvasmain.py", line 1605, in save_swp_to
Pickler(f, document).dump(diff)
AttributeError: Can't pickle local object 'SchemeEditWidget.__saveWindowGroup.<locals>.store_group.<locals>.redo'
```
* Add notifier signal for `Scheme.window_group_presets`
* Remove use of SimpleUndoCommand with local closure thunks. Instead implement a dedicated command.
* Add simple test

[FIX] Window Group Undo/Redo

---

orangecanvas/scheme/tests/test_widgetmanager.py
orangecanvas/scheme/widgetmanager.py

Since gh-118 widget manager does not create widgets on double click if in OnDemand creation mode (e.g. if 'freeze' action is toogled on in canvas). 
Remove an erroneous check.

[FIX] widgetmanager: Fix widget creation with OnDemand policy

---

setup.py

Mouse wheel scrolling was crashing for PyQt < 5.12.

Raise AnyQt to 0.0.11 to fix mouse wheel scrolling

---

orangecanvas/gui/toolbox.py
orangecanvas/gui/utils.py

On Mac, a mouse plugged in and 'Show scroll bars automatically based on mouse or trackpad' selected in General System Preferences, the `SH_ScrollBar_Transient` style hint will at first act as if the scrollbar is transient. After a few moments, it will correctly report that the scrollbar is not transient. This resulted in the toolbox being slightly obscured by the scrollbar.
This change stores the sizehint in the instance, and schedules a geometry update if it's changed, correctly updating the size of the toolbox.

toolbox: Update geometry on scrollbar style (transient) changed

---

orangecanvas/application/canvasmain.py
orangecanvas/application/tests/test_mainwindow.py
orangecanvas/document/schemeedit.py
orangecanvas/scheme/widgetmanager.py
orangecanvas/utils/pickle.py

Regarding swp crash recovery:
- Add support for annotations
- Fix restoring node properties
- Fix deleting nodes
- Fix clearing swp on a type of workflow save

Crash recovery fixes

---

orangecanvas/document/quickmenu.py
orangecanvas/styles/orange.qss

The main reason I wanted to remove categories from the quickmenu by default is because it was easy to hover over a category accidentally while trying to select an item, as the menu typically appears to the bottom-**right** of the cursor.
From what I understand, this is also the reason 'sloppy' category selection logic was implemented, such that a category is only selected after a certain time of hovering over it.
Moving the categories to the right of the menu alleviates this problem.

Fixup quickmenu UX

---

orangecanvas/application/addons.py
orangecanvas/application/application.py
orangecanvas/application/canvasmain.py
orangecanvas/application/tests/test_mainwindow.py
orangecanvas/help/manager.py
orangecanvas/help/provider.py
orangecanvas/help/tests/test_provider.py
orangecanvas/utils/asyncutils.py
orangecanvas/utils/pkgmeta.py
orangecanvas/utils/qobjref.py
orangecanvas/utils/tests/test_qobjref.py
setup.py

Currently the help system hits the network as soon as it is created (if any registered help entry point does not have locally installed help files) i.e. at main window creation time.
Initialize the help providers only when help is requested. Run the query as async task.

[ENH] Help refactor

---

orangecanvas/application/canvasmain.py
orangecanvas/gui/toolgrid.py

Last time on toolbox chronicles, elision was eliminated, but some of the names were pretty wide and close to the button edges. This change widens the toolbox by 12 pixels to make it prettier.
Also, if the Principal Component Analysis widget is called PCA, and the Multi-Dimensional Scaling widget is called MDS, can we call the Stochastic Gradient Descent widget SGD? Either by setting a short name (visible only in the toolbox), or renaming the widget itself. We could also rename PCA/MDS to their full names and set their short name to PCA/MDS.

canvasmain: Widen toolbox icons slightly

---

orangecanvas/application/addons.py
orangecanvas/application/application.py
orangecanvas/application/canvasmain.py
orangecanvas/application/tests/test_application.py
orangecanvas/main.py
orangecanvas/utils/after_exit.py
orangecanvas/utils/shtools.py
orangecanvas/utils/tests/test_after_exit.py

This PR and https://github.com/biolab/orange3/pull/5064, are separate (do not depend on each other), but when both of them are used together, Orange will restart upon installing an addon, instead of just closing.
The main package is moved to the top of the list, and the Add-ons window is renamed.
Also, question @ales-erjavec, why is `QTimer.singleShot` used to invoke QApplication methods? 49e8fb9 changes the first call, because otherwise exit is invoked before the user has a chance to go through the windows' "Do you wish to save?" dialogues. Does this break anything?

Restart + Small style changes for Add-ons dialogue

---

orangecanvas/canvas/items/linkitem.py
orangecanvas/canvas/items/nodeitem.py
orangecanvas/canvas/items/tests/test_linkitem.py
orangecanvas/canvas/items/tests/test_nodeitem.py
orangecanvas/canvas/scene.py
orangecanvas/canvas/tests/test_scene.py
orangecanvas/document/interactions.py
orangecanvas/document/schemeedit.py
orangecanvas/scheme/scheme.py
orangecanvas/utils/mathutils.py

Hold shift to show the currently hovered anchor's channels. You can drag from channel to channel, channel to node, node to channel, or from channel to anywhere (and add a new node).
This isn't quite finished, but it's far enough to be usable. Anyone want to give it a try? :)
TODO are tests, some stylistic changes, and fixing some bugs, like this one:
This will need to be fixed in `orangecanvas.canvas.layout.AnchorLayout`, specifically, instead of getting the points' positions directly from the objects' scene positions, it will need to map the positions from the uniform positions' percentage values on the anchor. (just writing this down for future reference)

[ENH] Visible channels on widget anchors

---

orangecanvas/canvas/items/nodeitem.py

Network Explorer was crashing.
This isn't pretty, I thought there were no five-channel widgets.

nodeitem: Fix five channel open anchor

---

orangecanvas/canvas/items/nodeitem.py

The channel anchor are unreadable when using dark style.
Use 'pallete(base)' for background color instead of fixed white color.

nodeitem: Use 'pallete(base)' for background color

---

orangecanvas/document/interactions.py
orangecanvas/document/usagestatistics.py

Sorry for the last minute.
Adds booleans for open sink/source signal anchors in UsageStatistics.

usagestatistics: Track open anchors

---

orangecanvas/document/interactions.py

If you try to add a new node via releasing a link on blank canvas, but you first hover over a widget's anchor, it silently fails to add the node.
This PR should fix this behavior.

interactions: Fix nodes sometimes not adding

---

orangecanvas/document/commands.py

Fixes a small bug I encountered while working on some yet-unpublished stuff.

commands: Fix UndoCommand wrong-order initialization

---

orangecanvas/canvas/items/graphicstextitem.py
orangecanvas/document/schemeedit.py

* On Windows the text is invisible (same color as the background) when trying to edit the node name.
* Drag/Drop a new node from the toolbox, press edit shortcut (<kbd>F2</kbd>), the name has visual appearance as editable, but does not actually have the keyboard focus, which remains with the toolbox.
* Update the item text color when editing.
* Ensure the view has focus when starting the node name edit.

[FIX] Inline node edit palette and focus

---

orangecanvas/document/quickmenu.py

Problem: as I started typing "dat" I saw "datasets" as a top option. Then I added "a", so I had "data", which put all widgets with "data" in front. I started pressing enter before typing the final "a", because the correct widget was already selected. I got something else instead of the "Datasets" I really wanted. :(
This PR decreases re-sorting frequency while still keeping the most obvious matches on top.

quickmenu: do not sort subword matches preferentially

---

docs/source/orangecanvas/document.interactions.rst
docs/source/orangecanvas/document.rst
orangecanvas/application/canvasmain.py
orangecanvas/application/canvastooldock.py
orangecanvas/application/widgettoolbox.py
orangecanvas/canvas/scene.py
orangecanvas/document/interactions.py
orangecanvas/document/schemeedit.py
orangecanvas/document/tests/test_schemeedit.py
orangecanvas/gui/test.py
orangecanvas/utils/__init__.py
setup.py

Ref:  https://github.com/biolab/orange3/issues/4918
Implement plugin support for handling canvas drop events.

[ENH] Plugin drag/drop support

---

orangecanvas/preview/scanner.py

* Preview render (Browse Recent, Example Workflows) renders node anchors in the wrong position
* One node in rendered selected
* Disable animations when rendering preview
* Deselect all items

[FIX] Workflow preview render

---

orangecanvas/canvas/items/graphicstextitem.py
orangecanvas/canvas/items/tests/test_graphicstextitem.py
orangecanvas/document/schemeedit.py
orangecanvas/document/tests/test_schemeedit.py
orangecanvas/gui/test.py

Fixes: https://github.com/biolab/orange3/issues/5379
Reimplement QGraphicsTextItem.contextMenuEvent for Qt >= 5.15.1,<6.0.0
Opening a context menu on an editable QGraphicsTextItem segfaults in Qt >=5.15.1,<6.0.0 ([QTBUG-88309](https://bugreports.qt.io/browse/QTBUG-88309))

[FIX] Segfault on right click on editable text item

---

orangecanvas/document/schemeedit.py

'Inline' node title editing via right click when selected (https://github.com/biolab/orange-canvas-core/pull/172) starts edit and immediately opens a context menu. Only left click should start edit. <s>Can also crash on Big Sur (https://github.com/biolab/orange3/issues/5379)</s> (QTBUG-88309 is the cause; present in Qt >=5.15.1)
Only start edit on left button click.

[FIX] schemeedit: Begin name edit only on left button click

---

orangecanvas/utils/after_exit.py

Ref: https://github.com/biolab/orange3/issues/5356
Pipe output to /dev/null

[FIX] after_exit: Pipe output to /dev/null

---

orangecanvas/canvas/items/linkitem.py

Ref gh-182
Prefer no hinting on the rotated text.
This only slightly improves, but does not completely eliminate the problem on windows. It only disables horizontal hinting, vertical hinting is still performed (there is no way to turn it off).

[FIX] linkitem: Prefer no hinting on rotated text

---

orangecanvas/scheme/scheme.py

Is required by https://github.com/biolab/orange-widget-base/pull/151
Until now, canvas-core was not aware of changes to settings in widget-base. It only knew to call `sync_node_properties` to pack Settings when saving. This PR adds a `node_properties_changed` signal, intended to be emitted by subclasses of Scheme. (see corresponding widget-base PR)
I needed to solve this for the tutorial implementation. However, it should make the following UX improvements trivial to implement:
Also, it would be sensible to:

Scheme: Add node_properties_changed signal

---

orangecanvas/application/canvasmain.py

Ref: https://github.com/biolab/orange3/pull/5459
Always use absolute path for 'basedir'

canvasmain: Always use absolute path for 'basedir'

---

orangecanvas/application/canvasmain.py
orangecanvas/application/canvastooldock.py
orangecanvas/application/tests/test_canvastooldock.py

In Orange clicking the 'Data' category button in the tooldock when collapsed can raise an exception when the screen is small:
```
-------------------------- AttributeError Exception ---------------------------
File "/Users/aleserjavec/Documents/workspace/orange-canvas/orangecanvas/application/canvasmain.py", line 932, in on_quick_category_action
action = popup.exec(pos)
File "/Users/aleserjavec/Documents/workspace/orange-canvas/orangecanvas/application/canvastooldock.py", line 519, in exec
self.popup(pos)
File "/Users/aleserjavec/Documents/workspace/orange-canvas/orangecanvas/application/canvastooldock.py", line 512, in popup
geom = widget_popup_geometry(pos, self)
File "/Users/aleserjavec/Documents/workspace/orange-canvas/orangecanvas/application/canvast …
```

[FIX] Category popup geometry error

---

orangecanvas/scheme/scheme.py

When proposing links between source widget outputs and sink widget inputs, 
subclasses of an InputSignal type have smaller weights than the class itself.
Example:
When connecting a Corpus widget to an Extract Keywords widget, the signals are linked as expected (Corpus (type=Corpus) -> Corpus (type=Corpus)).
When inserting a Data Table widget in between, the signals are linked according to InputSignal type (Selected Data (type=Table) -> Words (type=Table), instead of Selected Data (type=Table) -> Corpus (type=Corpus)).
Consider `strict` and `dynamic` source-sink connections equally weighted.

Scheme: Propose dynamic Input

---

.github/workflows/run-tests-workflow.yml

Tests on master fail since release of qasync 0.19
Use qasync<0.19 when testing with PyQt5 5.9; qasync 0.19 is incompatible with PyQt5 5.9

ci: Use qasync<0.19 when testing with PyQt5 5.9

---

.github/workflows/run-docs-build.yml
.github/workflows/run-tests-workflow.yml

ubuntu-16.04 worker is no longer available.

[CI] gh-actions: Replace ubuntu-16.04 workers

---

.readthedocs.yml
docs/requirements-rtd.txt

RTD docs build fails due to mismatched sphinx and docutils versions.
Move package install into requirements-rtd.txt so it is installed in the same step as sphinx.

[FIX] readthedocs: Fix build error on readthedocs

---

orangecanvas/application/addons.py
orangecanvas/application/tests/test_addons.py

addons: handle add-on names containing hyphens

---

orangecanvas/gui/utils.py

Fixes: https://github.com/biolab/orange3/issues/5711
libffi 3.4.2 rejects small integer arguments in variable argument lists (https://github.com/libffi/libffi/releases/tag/v3.4.2)
Fully qualify the selector call so no varg processing takes place.

[FIX] macos_set_nswindow_tabbing: Fix definition for the objc_msgSend

---

orangecanvas/application/canvasmain.py
orangecanvas/canvas/view.py
orangecanvas/document/schemeedit.py
orangecanvas/gui/examples/dock.py
orangecanvas/scheme/widgetmanager.py

Our logs are full of warnings like:
DeprecationWarning: an integer is required (got type KeyboardModifiers).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python

Remove deprecation warnings due to QKeyboardSequence

---

orangecanvas/document/interactions.py

When in [open anchors mode](https://github.com/biolab/orange-canvas-core/pull/215) dragging a outgoing link back onto the node
itself would raise an: 
ValueError: min() arg is an empty sequence
in AnchorItem.signalAtPos
```
---------------------------- ValueError Exception -----------------------------
File "/home/ales/devel/orange-canvas-core/orangecanvas/canvas/scene.py", line 848, in mouseReleaseEvent
self.user_interaction_handler.mouseReleaseEvent(event):
File "/home/ales/devel/orange-canvas-core/orangecanvas/document/interactions.py", line 610, in mouseReleaseEvent
sink_signal = item.inputAnchorItem.signalAtPos(
File "/home/ales/devel/orange-canvas-core/orangecanvas/canvas/items/nodeitem.py", line 1024, in signalAtPos
return min(signalsToFind, …
```

[FIX] Fix error on link create

---

orangecanvas/canvas/items/annotationitem.py
orangecanvas/canvas/items/tests/test_annotationitem.py

Creating a text annotation on the canvas raises an error on Python 3.10
```
----------------------------- TypeError Exception -----------------------------
File "/home/ales/devel/orange-canvas-core/orangecanvas/canvas/items/annotationitem.py", line 82, in paint
text = metrics.elidedText(self.__placeholderText, Qt.ElideRight,
TypeError: elidedText(self, str, Qt.TextElideMode, int, flags: int = 0): argument 3 has unexpected type 'float'
-------------------------------------------------------------------------------
```
Replace use of QFontMetrics with QFontMetricsF

[FIX] annotationitem: Fix a implicit int cast error

---

orangecanvas/application/application.py

Fixes https://github.com/biolab/orange3/issues/5697 (https://github.com/biolab/orange3/issues/5697#issuecomment-1023175177)
Set `highDpiScaleFactorRoundingPolicy` to `PassThrough` when available (Qt5 >= 5.14). 
Add cmd parameter '-scale-factor-rounding-policy' to optionally override this while respecting QT_SCALE_FACTOR_ROUNDING_POLICY env variable. 
Some visual glitches w.r.t. the windows style are visible with PassThrough and 1.5 scale factor (e.g. on hover over a check box), Fusion style seems fine though.

[FIX] application: Set `highDpiScaleFactorRoundingPolicy` to PassThrough

---

orangecanvas/help/provider.py
orangecanvas/help/tests/test_provider.py

HtmlIndexProvider does not discover documentation build with docutils >= 0.17 because HTML format slight changed. They use section tag instead of div now for the section with a list of widgets.
Fix path to support both div and section tags

[FIX] HtmlIndexProvider: fix path to work with docutils >= 0.17

---

orangecanvas/application/canvasmain.py

Embeding a QWebEngineView can cause problems with remote ssh, RDP, ...
sessions
* biolab/orange3#5583
* biolab/orange3#5749

canvasmain: Prevent 'Help' window from docking

---

.github/workflows/run-tests-workflow.yml

Ubuntu workers fail with:
```
Get:12 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libxcb-render-util0 amd64 0.3.9-1build1 [9912 B]
Fetched 117 kB in 1s (114 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.2.6-0ubuntu0.1~20.04.1_amd64.deb  [40](https://github.com/biolab/orange-canvas-core/runs/5596587010?check_suite_focus=true#step:4:40)4  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libegl1_1.3.2-1~ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/m/mesa/libegl1-mesa_21.2.6-0ubuntu0.1~20.04.1_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe …
```

Fix failing ubuntu ci workers

---

.github/workflows/run-tests-workflow.yml
orangecanvas/application/application.py
orangecanvas/application/tests/test_application.py

Ref: https://github.com/biolab/orange3/discussions/5927
orange-canvas raises an error with Python <= 3.7 and PyQt5 >= 5.14  
```
...
File "/root/DATA/orange_env/lib/python3.7/site-packages/orangecanvas/application/application.py", line 190, in argumentParser
default=default,
File "/usr/local/python3/lib/python3.7/argparse.py", line 1362, in add_argument
type_func = self._registry_get('type', action.type, action.type)
File "/usr/local/python3/lib/python3.7/argparse.py", line 1304, in _registry_get
return self._registries[registry_name].get(value, default)
TypeError: unhashable type: 'dict'
```
This is due to https://bugs.python.org/issue16516
Wrap a dict.get bound method in a function.
Add test configuration that would have caught this.

[FIX] application: Fix argparse type error

---

orangecanvas/main.py

Since orange canvas log to file in default encoding (Windows-1252 on Windows) it fails on logging some strings. For example, the following code in the python script fails:
```
import logging
s = "✌🏼️"
log = logging.getLogger("__name__")
log.warning(s)
```
with:
```
File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\logging\__init__.py", line 1084, in emit
stream.write(msg + self.terminator)
File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u010d' in position 55: character maps to <undefined>
```
Log in `utf-8` encoding. If I understand correctly it can write to file anything …

[RFC][FIX] Log to file with utf-8 encoding

---

orangecanvas/scheme/readwrite.py
orangecanvas/scheme/tests/test_readwrite.py

Settings with NaN values can not be loaded.
To reproduce: Create a widget with a float setting. Assign the setting NaN value and save the workflow. When opening the workflow, the saved value of the setting is not used.
In case of NaN raise an exception when writing it into a string as a python literal.

readwrite: Load NaN setting

---

.github/workflows/run-tests-workflow.yml

Linux gh actions runners started failing with 'qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.'
Add libxcb-shape to installed linux system packages
Also update deprecated macos-10.15 runners

[MNT][CI] Add libxcb-shape to linux system packages

---

orangecanvas/document/interactions.py
orangecanvas/utils/__init__.py

The *canvas drop handlers* can sometimes have duplicated entries and present a selection menu. 
`entry_points()` can return duplicated entries when there are multiple `sys.meta_path` with `find_distributions()` defined, or if a same package is found in two different entries on `sys.path`
Iterate only over unique entry_points

[FIX] interactions: Iterate only over unique entry_points

---

orangecanvas/application/addons.py

When upgrading/installing an add-on that requires an orange3 update from the add-on dialogue, Orange's dependencies do not upgrade. For example:
- I have orange3==3.32
- I install orange3-text, which requires orange3==3.33
- Orange3 gets updated but not its dependencies (including orange-widget-base and orange-canvas-core)
- It caused Orange to stop working since Orange3 needs orange-canvas-core and widget-base versions higher than they ship with orange3==3.32
Adding the `--upgrade` option to the `pip install` command will also update other dependencies if necessary (`only-if-needed` is pip's current default strategy)

[FIX] Update necessary dependencies when installing addons (pip)

---

orangecanvas/application/canvasmain.py

Clearing the *.swp* file can raise an error when e.g. a workflow with a swp file is loaded from a read only filesystem or belonging to a different user...
Handle errors trying to remove .swp files

[FIX] canvasmain: Handle errors trying to remove swp files

---

.github/workflows/run-docs-build.yml
.github/workflows/run-tests-workflow.yml
.readthedocs.yml

* Add Python 3.11 to test matrices
* Drop Python 3.6 from test matrices
* Update used gh actions to avoid runner deprecation warnings

[CI] Add Python 3.11 to test matrices

---

orangecanvas/application/addons.py

If there is a network problem in `list_available_versions`, the add-on dialog becomes useless. It could allow at least uninstallation.
I changed `list_available_versions` to continue on network errors and gathers whatever info it can, so that the dialog still works for some actions. The first exceptions is still displayed in a dialog as before.

addons: list_available_versions continues with non-critical exceptions

---

orangecanvas/utils/localization/__init__.py
orangecanvas/utils/localization/tests/test_localization.py

To be used here and also in dependent projects (orange-widget-base, orange3, add-ons).
The function is not in module (i.e. file localization.py) but in package, so that we have a place where translations to other languages can drop modules with their specific functions.

Add function for English plural forms

---

orangecanvas/help/provider.py

Fixes https://github.com/biolab/orange-canvas-core/issues/250
Remove use of obsolete FollowRedirectsAttribute. setting RedirectPolicyAttribute already does the job.

[FIX] provider: Remove use of obsolete FollowRedirectsAttribute

---

orangecanvas/styles/__init__.py

When running from a git checkout on windows with git autocrlf set to true there are 
warnings printed on the console about missing .Dropdown.svg icon file.
Fix prefix path extraction regex.

[FIX] process_qss: Fix prefix path extraction regex

---

orangecanvas/application/canvasmain.py
orangecanvas/gui/windowlistmanager.py
orangecanvas/scheme/tests/test_widgetmanager.py
orangecanvas/scheme/widgetmanager.py

Since gh-248 <kbd>CMD+`</kbd> shortcut on macOS does not work properly.
Also the 'Raise Ancestors/Descendants' actions inserted into the widgets should be disabled when non applicable (i.e. have no ancestors/descendants)
* Do not double activate a window on<kbd>CMD+`</kbd>
* Enable/disable 'Raise Ancestors/Descendants' actions
* Also move 'Bring Widgets to Front' and 'Display Widgets on Top' to 'Windows' menu.

[FIX] Menu window list fixups

---

orangecanvas/application/canvasmain.py
orangecanvas/main.py

Orange installed from conda/pip does not have an icon (on Mac) 
Fixes: https://github.com/biolab/orange3/issues/6129
Set default application level window icon (special care must be taken so the default application icon does not override the "proxy icon" for file in the main window).

[FIX] Set default application level window icon

---

orangecanvas/canvas/view.py

Modern browsers allow zooming in without pressing shift on US keyboard (`Ctrl + +` is actually `Ctrl + Shift + =). So we are spoiled.
Qt's docs actually warn about this specific case (and they recommend caution): https://doc.qt.io/qt-5/qkeysequence.html#keyboard-layout-issues
I do not see any problems with allowing `Ctrl + =` too (do we use it anywhere else?). It does make the code slightly uglier. 
If accepted, this fixes biolab/orange3#6240.

Workflow zoom-in also works with Ctrl+= (forgotten shift)

---

orangecanvas/registry/base.py
orangecanvas/registry/tests/__init__.py
orangecanvas/scheme/node.py
orangecanvas/scheme/readwrite.py
orangecanvas/scheme/tests/test_nodes.py

Channels have names (for humans) and ids (for machines).
A workflow created in English version of Orange cannot be loaded in Slovenian Orange because channel names are translated. This change fixes that by using id's, which are not translated. This change will have effect after https://github.com/biolab/orange-widget-base/pull/229 is merged.
I think using id's in .ows is also better in principle.
For backward compatibility, `input_channel` and `output_channel` match by id and, as a fallback, by name. This will fail if id is the same as the name of another signal, which is unlikely. Besides, https://github.com/biolab/orange-widget-base/pull/229 shows a warning in such cases.

Refer to channels by ids, not their visible names when saving/loading

---

orangecanvas/scheme/signalmanager.py
orangecanvas/scheme/tests/test_signalmanager.py

Ref. https://github.com/biolab/orange3/issues/5720.
See description in the code.
Also see changes in https://github.com/biolab/orange-widget-base/pull/232. 
Usage example is shown in https://github.com/biolab/orange3/pull/6348.
This assumes that signal manager does not check that the type of the signal matches the defined type - as is currently the case. Should it ever check this, it will have to recognize lazy signals in check their wrapped types.

Add `LazyValue`s

---

orangecanvas/scheme/events.py
orangecanvas/utils/settings.py

Deprecation warnings when running with PyQt6 e.g.
```
/home/ales/devel/orange-canvas-core/orangecanvas/scheme/events.py:95: DeprecationWarning: QEvent constructor is deprecated
super().__init__(cast(QEvent.Type, etype))
```
Change type of event type constants.

[FIX] Fix PyQt6 warnings

---

orangecanvas/application/addons.py
orangecanvas/application/tests/test_addons.py

Ref: https://github.com/biolab/orange-canvas-core/pull/260#issuecomment-1463716149
A type error in addon dialog when toggling between installed/update/remove action states.
```
----------------------------- TypeError Exception -----------------------------
File "/home/ales/devel/orange-canvas-core/orangecanvas/application/addons.py", line 319, in editorEvent
checkstate = self.nextCheckState(checkstate, index)
File "/home/ales/devel/orange-canvas-core/orangecanvas/application/addons.py", line 332, in nextCheckState
return Qt.CheckState((state + 1) % 3)
TypeError: unsupported operand type(s) for +: 'CheckState' and 'int'
-------------------------------------------------------------------------------
```
* Fix a type error with PyQt6 CheckState
* Add test

[FIX] addons.py: Fix a type error with PyQt6 CheckState

---

orangecanvas/registry/discovery.py
orangecanvas/registry/utils.py

This PR changes the resolving the category name to follow this order,
- `NAME` from package globals,
- entry point from setup.py,
- the name deduced from qualified package name. This used to take the last part, but this is usually `"widgets"`. Now it takes the penultimate part in that case.
Previously, the first two points were reversed. I think package globals should have precedence because they are explicit.
Besides, the entry point is always defined (has to be, AFAIK), so the name from package globals was ignored. As result, we couldn't translate category names.

Category discovery: Improve logic for determining category name

---

orangecanvas/scheme/link.py

Ref: https://github.com/biolab/orange3/issues/6410#issuecomment-1508515214
Any error can happen in the link type resolution (i.e. when dragging a new link in the canvas).
Catch all errors in resolve_types

link: Catch all errors in resolve_types

---

orangecanvas/document/editlinksdialog.py
orangecanvas/document/tests/test_editlinksdialog.py

Make removal of connections more obvious
Closes https://github.com/biolab/orange-canvas-core/issues/258 
Better hint that clicking the connection will remove it.

[ENH] editlinksdialog: Indicate remove connection

---

orangecanvas/document/editlinksdialog.py
orangecanvas/document/tests/test_editlinksdialog.py

The Edit Links dialog has bad contrast with dark style.
Replace hardcoded colors with palette derived ones.
Before:
After:

[ENH] editlinksdialog: Replace hardcoded colors with palette derived ones

---

orangecanvas/application/application.py
orangecanvas/application/canvastooldock.py
orangecanvas/application/widgettoolbox.py
orangecanvas/canvas/items/nodeitem.py
orangecanvas/document/quickmenu.py
orangecanvas/gui/iconengine.py
orangecanvas/gui/svgiconengine.py
orangecanvas/gui/tests/test_iconengine.py
orangecanvas/gui/toolbox.py
orangecanvas/gui/utils.py
orangecanvas/registry/discovery.py
orangecanvas/registry/utils.py
orangecanvas/resources.py
orangecanvas/styles/__init__.py
orangecanvas/utils/image.py
setup.py

Fixes: gh-270
Color widget icons based on current palette where appropriate.
By default when running in dark mode the colors are inverted to fit the background to foreground grayscale range.
Note that 'Color' is quite badly drawn.
But also add support for explicitly using *palette styled* widget icons like in https://github.com/biolab/orange3/pull/6444

[ENH] Color styled widget icons

---

.github/workflows/run-tests-workflow.yml

PyQt6 6.5 tests fail on ubuntu-20.04 due to
https://www.riverbankcomputing.com/pipermail/pyqt/2023-June/045313.html
Use ubuntu-22.04 image

[MNT] ci: Update ubuntu image for PyQt6 6.5 tests

---

orangecanvas/application/canvasmain.py
orangecanvas/application/tests/test_widgettoolbox.py
orangecanvas/application/widgettoolbox.py
orangecanvas/document/quickmenu.py
orangecanvas/gui/toolgrid.py
orangecanvas/registry/utils.py
orangecanvas/styles/orange.qss

Closes https://github.com/biolab/orange3/issues/6447
Implement filter/search for the widget toolbox.

[ENH ]Tool box filter

---

orangecanvas/scheme/signalmanager.py

As proposed by @ales-erjavec, this fixes https://github.com/biolab/orange3/issues/6583.
Lazy signals are evaluating before checking their types. *If the signal is of the correct type*, it would eventually be evaluated anyway, so we don't lose anything.
If lazy signals had type hints, we could check the type before evaluation and save some memory when signals don't match. But this is an error condition and I won't lose sleep over it. Also, type hints would in most cases need to be added "manually" as an additional argument to `LazyValue`. In most widgets we would forger to do it, so signal manager would have to fall back to evaluation anyway.

Evaluate values of dynamic signals before type checking

---

.readthedocs.yml

RTD docs build [fails](https://readthedocs.org/projects/orange-canvas-core/builds/22141919/) due to dropped [system_packages](https://blog.readthedocs.com/drop-support-system-packages/) key 
Remove `system_packages` key

[MNT] readthedocs: Remove no longer supported 'system_packages'

---

orangecanvas/utils/asyncutils.py
setup.py

Requesting help for a widget when using the latest released qasync v0.24.2 fails with an exception
```
File "/Users/aleserjavec/workspace/orange-canvas/orangecanvas/application/canvasmain.py", line 2352, in run
url = await query_coro
^^^^^^^^^^^^^^^^
File "/Users/aleserjavec/workspace/orange-canvas/orangecanvas/help/manager.py", line 127, in search_async
return await provider.search_async(desc, timeout=timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/aleserjavec/workspace/orange-canvas/orangecanvas/help/provider.py", line 133, in search_async
await asyncio.wait_for(reply_f, timeout)
File "/Users/aleserjavec/.local/opt/python3.11/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 439, in wait_for
loop = …
```

[FIX] Ensure qasync loop is set as running

---

orangecanvas/canvas/items/nodeitem.py

When Shift dragging a new connection from an expanded channel anchor to an empty spot on the canvas and not completing the interaction (i.e. canceling it) then the connection anchor remains open.
Similar to gh-272 except that the connection needs to be dragged to an empty spot and then closing the new node menu.
Update anchor positions when changing state.

[FIX] nodeitem: Update opened anchor on link completion

---

orangecanvas/application/tests/test_widgettoolbox.py
orangecanvas/application/widgettoolbox.py

Running unittests on Python 3.12 aborts with 
```
...
test_filter (orangecanvas.application.tests.test_widgettoolbox.TestWidgetToolBox.test_filter) ... ok
File "/home/ales/devel/orange-canvas-core/orangecanvas/application/widgettoolbox.py", line 161, in actionEvent
button = self.buttonForAction(event.action())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ales/devel/orange-canvas-core/orangecanvas/gui/toolgrid.py", line 345, in buttonForAction
index = actions.index(action)
^^^^^^^^^^^^^^^^^^^^^
ValueError: <PyQt6.QtGui.QAction object at 0x7fd2b44b48a0> is not in list
Fatal Python error: Aborted
```
Handle model reset and use model reset in test tearDown to avoid errors in tests.

[FIX] widgettoolbox: Fix WidgetToolBox tests with Python 3.12

---

.readthedocs.yml

RTD docs build [fails](https://readthedocs.org/projects/orange-canvas-core/builds/22266727/) due to missing [build.os key](https://blog.readthedocs.com/use-build-os-config/) 
Add build.os key

[MNT] readthedocs:  Add build.os key

---

orangecanvas/canvas/tests/test_view.py
orangecanvas/canvas/view.py

Using pinch gesture on the canvas when using PyQt6 causes an error
```
----------------------------------------------------------------------
...
File "/home/ales/devel/orange-canvas-core/orangecanvas/canvas/view.py", line 199, in __setZoomLevel
self.centerOn(anchor + diff)
~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for +: 'QPoint' and 'QPointF'
----------------------------------------------------------------------
```
Cast the anchor to QPointF

[FIX] view: Fix a type error with PyQt6

---

.github/workflows/run-tests-workflow.yml
orangecanvas/application/tests/test_main.py
orangecanvas/gui/windowlistmanager.py

Test with Python 3.12
Add Python 3.12 to test matrices

[CI] Add  Python 3.12 to CI tests

---

orangecanvas/application/tests/test_addons_utils.py
orangecanvas/application/utils/addons.py

On some corporate computers, it may be the issue that either the cache directory doesn't have permission to write or an existing cache file lacks reading permission. It happened to one of our customers. The cache file was successfully created, but the next time it tried to be read, it no longer had permissions.
When there is no read or write permission, ignore the cache.

[FIX] Addons - Do not use cache when no permission to write

---

docs/source/conf.py
orangecanvas/application/addons.py
orangecanvas/application/canvasmain.py
orangecanvas/application/examples.py
orangecanvas/application/tests/test_addons.py
orangecanvas/application/tests/test_addons_utils.py
orangecanvas/application/tests/test_main.py
orangecanvas/application/utils/addons.py
orangecanvas/config.py
orangecanvas/document/interactions.py
orangecanvas/document/tests/test_schemeedit.py
orangecanvas/gui/tests/test_splashscreen.py
orangecanvas/help/manager.py
orangecanvas/help/tests/test_manager.py
orangecanvas/preview/tests/test_previewbrowser.py
orangecanvas/registry/description.py
orangecanvas/registry/discovery.py
orangecanvas/registry/tests/test_discovery.py
orangecanvas/styles/__init__.py
orangecanvas/utils/pkgmeta.py
orangecanvas/utils/tests/test_pkgmeta.py
setup.py

[pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html)  is deprecated.
Remove/replace use of pkg_resources with importlib.metadata, importlib.resources, pkgutil and packaging.
This also bumps version to 0.2.* because it is backwards incompatible due to differences in exposed types in the discovery process. This should trigger the `orange-canvas-core>=0.1.30,<0.2a` condition in https://github.com/biolab/orange3/blob/78f7b30a89a7b78ef6442f0b828f41a6f5c27951/requirements-gui.txt#L1

[ENH] Remove use of pkg_resources

---

orangecanvas/application/application.py
orangecanvas/application/tests/test_application.py
orangecanvas/application/tests/test_main.py
orangecanvas/main.py

Fixes https://github.com/biolab/orange3/issues/6653
Reconfigure stylesheet on application palette change

[FIX] Reconfigure stylesheet on application palette change

---

.github/workflows/run-docs-build.yml
.github/workflows/run-tests-workflow.yml

Various actions raise warnings 
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
Update actions

[MNT] ci: Update various action versions

---

orangecanvas/application/canvasmain.py
orangecanvas/application/tests/test_mainwindow.py
orangecanvas/canvas/scene.py

Fixes https://github.com/biolab/orange3/issues/6777
The results are less then stellar though. All SVG icons get rasterized.
* Save workflow image to SVG 
* Also make the save ows dialog window modal instead of application modal.

[ENH] Save workflow image to SVG 

---

orangecanvas/utils/tests/test_overlay.py

Tests fail with a segmentation fault when running under pytest>=8.2 
* Dispatch to super class setUp/tearDown in TestOverlay
* Replace use of Mock in signal connection with QSignalSpy

[FIX] Fix test_overlay

---

orangecanvas/document/interactions.py

Fixes https://github.com/biolab/orange3/issues/6796
Add more quick tip for text annotations

[ENH] Text Annotations quick tip text

---

orangecanvas/application/settings.py
orangecanvas/config.py
orangecanvas/main.py
orangecanvas/utils/localization/__init__.py

This adds a language selector to the settings dialog. It will allow us to prepare multilingual distributions of Orange, which we urgently need for various education-related projects.
The change is only visible if distribution includes message files that are prepared by (so far unpublished new version of) Trubar.
Caveats:
- Language must be detected at the very beginning because some modules (even modules like `Orange.data.table` may already include translated strings). This is why language is read from `QSettings(QSettings.IniFormat, QSettings.UserScope, organization, application)` and not just `QSettings()` because `QApplication` is not set up at that point yet. Organization and application are specified in Trubar's configuration files, to allow Trubar to insert the following at the …

Add language setting and translation function

---

orangecanvas/application/application.py

Fixes: https://github.com/biolab/orange3/issues/6826
Qt5 uses obsolete MS Dlg Shell 2 'virtual' font by default.
As per https://github.com/musescore/MuseScore/pull/5791#issuecomment-596669064 `QApplication.font("QMessageBox")` has the correct computed font so set that as the default.

[FIX] application: Fix default application font on windows (QTBUG-61707)

---

setup.py

Fixes https://github.com/biolab/orange3/issues/6831
Specify minimum importlib-metadata version

[FIX] setup.py: Specify minimum importlib-metadata version

---

.github/workflows/run-docs-build.yml
.github/workflows/run-tests-workflow.yml
.readthedocs.yml
docs/requirements-rtd.txt
orangecanvas/scheme/readwrite.py
orangecanvas/scheme/tests/test_readwrite.py
setup.py

Fixes: https://github.com/biolab/orange-canvas-core/issues/304
Replace use of deprecated ast classes

[MNT] readwrite: Replace use of deprecated ast classes

---

orangecanvas/styles/__init__.py

Fixes: https://github.com/biolab/orange3/issues/6837
This error causes missing dropdown indicators in the bottom toolbar
This does not apply and cannot be replicated using dark style
Fix package base path

[FIX] styles: Fix package base path (fixes dropdown indicators)

---

.github/workflows/run-docs-build.yml
.github/workflows/run-tests-workflow.yml
.readthedocs.yml
docs/requirements-rtd.txt
docs/source/conf.py
i18n/si/msgs.jaml
pyproject.toml
setup.py

@markotoplak, could you check that this is what we want? 
~~It should work like in Image Analytics, except that in Image Analytics we assume that Trubar is installed (because Orange requires it), while here we don't.~~
This should work as in Image Analytics, except that it does not require Trubar.
If you confirm this, I'll make the equivalent PR for orange-widget-base and orange3.

[ENH] Setup: translated packages

---

i18n/si/msgs.jaml
orangecanvas/document/schemeedit.py
orangecanvas/document/tests/test_schemeedit.py

Closes: https://github.com/biolab/orange3/issues/6893
Avoid replicated node renumbering on paste

[FIX] schemeedit: Avoid replicated node renumbering on paste

---

.github/workflows/run-tests-workflow.yml
orangecanvas/application/application.py

Wrong logic in `fix_qt_plugins_path`
Was broken for PyQt5 due to early return
Fix qt plugins search logic error

[FIX] application.py: Fix qt plugins search logic error

---

orangecanvas/utils/localization/__init__.py

In certain set of circumstances, the code that loads localization JSONs could raise a `ResourceWarning: unclosed file`. Using context managers ensures that the file is closed after loading.
In my case, the `ResourceWarning` was raised when collecting tests with `pytest` in a package that uses `orange-canvas` but I couldn't produce a minimal example, sorry.

Ensure that JSON files are proprely closed in localization

---

i18n/si/msgs.jaml
orangecanvas/application/application.py

Fixes #314. I did not test how this looks on Windows, but it should not change anything since both 32 and 64-bit windows are `win32`

[FIX] Fix bold fonts on Qt5 on Macs (apply QTBUG-58610 fix only on Windows)

---

orangecanvas/application/utils/addons.py

Fixes: https://github.com/biolab/orange3/issues/6938
Remove '--satisfied-skip-solved' flag from conda command

[FIX] Fix addon updates (remove '--satisfied-skip-solved' flag from conda command)

---

i18n/si/msgs.jaml
orangecanvas/help/manager.py
orangecanvas/utils/pkgmeta.py
orangecanvas/utils/tests/test_pkgmeta.py

Fixes: https://github.com/biolab/orange-canvas-core/issues/317
Since some time pip install -e ... installs a ${NAME}.dist-info dir into site-packages with a direct_url.json recording its origin.
This confuses importlib.metadata (https://github.com/python/cpython/issues/96144)
Support PEP-610 direct_url.json

[FIX] pkgmeta: Support PEP-610 direct_url.json

---

orangecanvas/application/addons.py

Fix https://github.com/biolab/orange-canvas-core/issues/325 (or at least attempt)
Queue the exit call instead of calling it directly. This seems to fix the issue, but I am not sure why.

[FIX] addons: Use QTimer.singleShot to exit/restart

---

i18n/si/msgs.jaml
orangecanvas/canvas/items/linkitem.py
orangecanvas/canvas/items/tests/test_linkitem.py

I drafted something and I know it's ugly:
- It assumes that `__dynamicEnabled` being false is always a consequence of type mismatch. (True for now, but not necessarily in the future.)
- It doesn't update the tooltip if the user renames the source or sink widget after sending the data. (Minor glitch, but still...)
The latter would require connecting some distant signals, the former requires checking the reason for mismatch (i.e. comparing the signal types).
@ales-erjavec: is this a useful start or would you approach it differently?
@ajdapretnar: is the message OK?

Signal manager: Add a tooltip about mismatching types

---

.github/workflows/run-docs-build.yml
.github/workflows/run-tests-workflow.yml

GH Actions runner images are deprecated
Update ubuntu-20.04 to ubuntu-22.04 and windows-2019 to windows-2022

[MNT] CI: Update runners

---

orangecanvas/document/interactions.py
orangecanvas/document/schemeedit.py

Hello,
Like in description: _Added flag for keep state across whole user interactions (in UserInteraction class) and implement it for ArrowAnnotation._
I Pull Request this feature, because I think this is some kind of intuitive and decrease mouse move when we repeat the same operation.
Of course `shift` is my personal choice, so if `ctrl` be better, the change is straightforward.

[ENH] UserInteraction can be extended by shift.
