biolab/orange-canvas-core

- orangecanvas/gui/dropshadow.py
- orangecanvas/gui/tests/test_dropshadow.py
Fixes gh-5
Invalidate the cached pixmap for devicePixelRatio change.
> [FIX] dropshadow: Device pixel ratio change

- orangecanvas/application/addons.py
Fix a permission error due to `tempfile.NamedTemporaryFile`'s O_TEMPORARY flag on windows.
https://bugs.python.org/issue14243
> [FIX] addons: Fix permission error on windows

- orangecanvas/document/quickmenu.py
The program sometime segfaults when the mouse cursor is above the view and the
current index is moved above or below the viewport.
This is due to the use of 'entered' signal from the view which gets
emitted when the view scrolls the view to the current index when it
is moved outside the viewport bounds (via up/down keys).
The `__onEntered` slot then sets the current index again,
before the view fully processed the previous move (the `__onEntered`
slot already contains one note and a 'workaround' for a similar or
maybe even exact issue).
Replace the use of 'entered' signal from the view with a mouse move
event filter on the view.
> [FIX] quickmenu: Fix a segfault in up/down keyboard navigation

- orangecanvas/application/canvasmain.py
- orangecanvas/gui/stackedwidget.py
- orangecanvas/styles/orange.qss
- orangecanvas/utils/overlay.py
- orangecanvas/utils/tests/test_overlay.py
A refactored implementation of canvas notifications, migrated from orange3.
> [ENH] Canvas Notifications

- orangecanvas/utils/settings.py
Remove use of '_pickledvalue' in utils/settings.py
'Settings' used to store values, for which the explicit type was not registered in default' slots, by wrapping it in a _pickledvalue, so it would be pickled and unpickled when read from .ini files by PyQt.
But this creates a mess when reading the settings back with plain QSettings with the specified type 
and default value.
This was a misfeature. 
'_pickledvalue' class is made 'non constructable' except when unpickled to presserve backcompatibility.
> [FIX] utils/settings: Remove use of '_pickledvalue'

- orangecanvas/gui/tooltree.py
Check that the `sourceModel()` is not None in FlattenedTreeItemModel
Getting intermittent errors during local unittest runs.
The QAbstractProxyModel's sourceModel is set to None (null) when the the source is deleted (via destroyed signal).
> [FIX] gui/tooltree: Fix type error when the sourceModel is None

- orangecanvas/canvas/items/nodeitem.py
> Change how selected nodes look on canvas

- orangecanvas/document/schemeedit.py
In addition to the existing duplicate action (Ctrl+D), copy/paste actions was added (Ctrl+C/Ctrl+V). This is a feature requested by users in the past – of my personal opinion, Ctrl+C –> Ctrl+V is a convention users are used to for duplication.
> Implement copy/paste for canvas nodes and links

- orangecanvas/canvas/items/linkitem.py
- orangecanvas/canvas/items/nodeitem.py
- orangecanvas/canvas/scene.py
- orangecanvas/document/interactions.py
- orangecanvas/document/schemeedit.py
> Style node anchors and link lines

- orangecanvas/canvas/scene.py
> CanvasScene: Highlight widgets on addition

- orangecanvas/document/schemeedit.py
When adding a node for the first time using the menu, the undo action remains disabled.
E.g. right or double click select a node from the list, press <kbd>Ctrl + U</kbd>
When temporarily disabling a undo-redo action, restore the action's state to matche the underlying stack's state.
> schemeedit: Fix Undo/Redo action re-enable

- orangecanvas/document/schemeedit.py
- orangecanvas/document/usagestatistics.py
Add two new events to usage statistics:
- Widget insertion via drag onto compatible link
- Widget insertion via right-click on link and choosing 'Insert Widget'
> usagestatistics: Add widget insertion events to usage statistics

- orangecanvas/document/schemeedit.py
**Issue** 
https://github.com/biolab/orange3/issues/4136
Middle-click a link to remove it.
> schemeedit: Remove link on middle-click

- orangecanvas/application/addons.py
https://github.com/biolab/orange3/issues/4121
Catch more errors
> addons: Fix have_install_permissions

- orangecanvas/canvas/items/nodeitem.py
Repeated work in every paint call
Cache the background shape between paint calls
> nodeitem: Optimize text background drawing (when selected)

- orangecanvas/application/addons.py
Fixes https://github.com/biolab/orange3/issues/4018.
Are there any possible errors that are not internet-related? Or would this message cover it all?
> Informative message for add-on dialogue

- orangecanvas/application/addons.py
- orangecanvas/application/canvasmain.py
- orangecanvas/application/tests/test_addons.py
- orangecanvas/application/tests/test_mainwindow.py
- orangecanvas/gui/utils.py
- orangecanvas/scheme/readwrite.py
- orangecanvas/scheme/signalmanager.py
- orangecanvas/utils/__init__.py
- orangecanvas/utils/qinvoke.py
- orangecanvas/utils/tests/test_qinvoke.py
- setup.cfg
Loading a workflow containing nodes from add-ons fails if the add-ons are not installed.
Detect missing packages and offer to install them via the add-ons dialog.
> [ENH] Detect and install missing add-ons when when loading a workflow

- orangecanvas/application/outputview.py
Fixes gh-74
* Complete the TextStream's I/O interface
> outputview: Complete the TextStream's I/O interface

- orangecanvas/canvas/items/annotationitem.py
Ref gh-73
Remove <kbd>Alt</kbd> modifier for context menu.
> annotationitem: Remove Alt modifier for context menu

- orangecanvas/document/tests/test_usagestatistics.py
I had a test fail on this once, possibly because of the plagiarized class name?
> [MINOR] Fix statistics test classname

- orangecanvas/application/application.py
- orangecanvas/application/settings.py
- orangecanvas/config.py
- orangecanvas/main.py
- orangecanvas/styles/__init__.py
Ref gh-67
Add style options to settings dialog
> [ENH] Style settings

- orangecanvas/canvas/items/nodeitem.py
- orangecanvas/canvas/items/tests/test_nodeitem.py
Start a spinner animation on a timeout when no new progress is set
> [ENH] nodeitem: Indeterminate progress spinner

- orangecanvas/canvas/view.py
Currently, if you hold shift and scroll, each turn of the scroll wheel will scroll a full horizontal distance (at least with my mouse).
I've changed this to scroll more smoothly.
Also, if the vertical scrollbar isn't visible and a user's trying to scroll, it'll scroll horizontally.
> [ENH] Smooth horizontal scrolling

- orangecanvas/application/canvasmain.py
Fixes gh-91, gh-92
Handle errors in save/load swp files.
> [FIX] Handle save/load swp errors

- orangecanvas/scheme/tests/test_annotations.py
> test_annotations: Fix a test so it actually runs

- orangecanvas/application/addons.py
Ref: https://github.com/biolab/orange3/issues/4649#issuecomment-615498519
Remove pip constraint pinning.
> addons: Remove installation with constraints pinning

- orangecanvas/canvas/view.py
Add pinch to zoom in the main canvas workflow view.
> [ENH] view: Add pinch to zoom to workflow view

- .travis.yml
- appveyor.yml
> [CI] Add PyQt5 5.15.0 to test matrix

- orangecanvas/application/addons.py
- orangecanvas/application/canvasmain.py
> canvasmain: Remove overspecific application branding

- orangecanvas/application/canvasmain.py
- orangecanvas/application/tests/test_mainwindow.py
Ref gh-54
Add connect_output_stream method to stream extra output to output view. Preserved by create_new_window.
> [ENH] canvasmain: Add connect_output_stream method

- orangecanvas/document/schemeedit.py
Fixes https://github.com/biolab/orange-widget-base/issues/39
> schemeedit: Allow insertion of nodes which change signal type

- orangecanvas/application/addons.py
- orangecanvas/application/tests/test_addons.py
Fixes https://github.com/biolab/orange3/issues/4880
Keep the QThread instance alive until the thread finishes.
> [FIX] Fix addons thread delete ordering

- orangecanvas/application/addons.py
Resolves biolab/orange3#4797
Solution obtains requirements from project info, determines a set of core packages and checks whether some of these core packages are updated directly or indirectly as a requirement. Longer chains (requirement of a requirement) are not detected. It shows a warning window with a list of core packages that will be upgraded.
However, requirements of many Orange addons aren't available on pypi (e.g. `requires_dist` in https://pypi.org/pypi/Orange3-Text/json) as pypi extracts that from uploaded wheels.
> [ENH] addons: warn about upgrades of core packages

- orangecanvas/canvas/items/linkitem.py
- orangecanvas/canvas/items/nodeitem.py
- Smooth node hover effects on quick hover/unhover (before, the hover shadow just stayed there)
- More appropriate colors for node anchor drags, disable shadow on drag
> Hover visual adjustments

- orangecanvas/document/schemeedit.py
- orangecanvas/utils/__init__.py
https://github.com/biolab/orange3/issues/4909
Preserve existing sink/source channels in insertNode if possible.
> schemeedit: Preserve existing sink/source channels in insertNode

- orangecanvas/document/quickmenu.py
- orangecanvas/registry/description.py
> quickmenu: Improve search functionality

- .travis.yml
- appveyor.yml
- setup.py
Closes gh-83
Raise minimum supported python version to 3.6 and remove 3.5 from CI
> setup.py: Raise minimum supported python version to 3.6

- orangecanvas/application/canvasmain.py
- orangecanvas/canvas/items/graphicstextitem.py
- orangecanvas/canvas/items/linkitem.py
- orangecanvas/canvas/items/nodeitem.py
- orangecanvas/canvas/scene.py
- orangecanvas/document/schemeedit.py
- orangecanvas/document/tests/test_schemeedit.py
- orangecanvas/gui/toolbox.py
- orangecanvas/utils/__init__.py
Closes https://github.com/biolab/orange-canvas-core/issues/46
Implement link selection and deletion.
> [ENH] Link Selection

- orangecanvas/application/canvasmain.py
Fixes the actual bug behind #92.
> canvasmain: Ask load swp only on valid ows

- orangecanvas/application/settings.py
Before:
After:
@markotoplak What does this look like on Linux?
> settings: Fix vertically misaligned form layout labels

- orangecanvas/canvas/view.py
A big difference between Orange and a Jupyter Notebook is that workflows tend to grow horizontally, while a notebook grows vertically. I think humans are just used to content continuing in a downward direction. Text is read horizontally but is broken into lines arranged vertically. I thought about ways one could do this with a data mining workflow, but nothing clean comes to mind.
This is an effort toward increasing workflow readability, by scrolling horizontally also when one tries to scroll off the edge of a workflow that doesn't vertically fit into the window.
**Note**
The previous horizontal scrolling change caused a bug in PyQt < 5.12 (the constructor signature for QWheelEvent changed). Although Orange3 specifies PyQt5>=5.12 in its requirements, there's a lot of reports regarding …
> view: Scroll horizontally if trying to scroll off edge

- orangecanvas/application/application.py
https://github.com/biolab/orange3/issues/5034
Check for the existence of styleHints
> [FIX] application: Check for the existence of styleHints

- orangecanvas/gui/toolgrid.py
I've increased the maximum text width a bit, making most widget names not elide. Admittedly, it looks a bit weird where there's text close to each other:
These two widgets seem to be the only case.
I'd rather fix this by either increasing the margin between buttons, changing the column count, or reordering Visualize widgets such that Pythagorean Tree and Forest aren't next to each other in a row.
There's only a couple eliding names left in core:
- Stochastic Gradient D...
- Distance Transforma...
- Correspon... Analysis
- Save Dista... Matrix
- Self-Organi... Map
> toolgrid: Rewrite toolbox text elision

- orangecanvas/canvas/items/graphicstextitem.py
- orangecanvas/canvas/items/linkitem.py
- orangecanvas/canvas/scene.py
> linkitem: Show channel name on hover

- .travis.yml
- appveyor.yml
> [CI] Add Python 3.9 to ci tests

- orangecanvas/application/addons.py
I didn't know I needed this but now I can't live without it.
> addons: Remove orange3- from names

- orangecanvas/application/application.py
- orangecanvas/application/tests/test_application.py
- orangecanvas/utils/after_exit.py
- orangecanvas/utils/shtools.py
- orangecanvas/utils/tests/test_after_exit.py
Ref gh-139
Ref gh-153
Add utilities for implementing application restart.
> [ENH] Application restart / run command after exit

- .github/workflows/run-docs-build.yml
- README.rst
- docs/requirements-rtd.txt
- docs/source/orangecanvas/document.schemeedit.rst
- docs/source/orangecanvas/gui.lineedit.rst
- docs/source/orangecanvas/gui.toolgrid.rst
- docs/source/orangecanvas/scheme.events.rst
- docs/source/orangecanvas/scheme.node.rst
- docs/source/orangecanvas/scheme.signalmanager.rst
- orangecanvas/scheme/events.py
- orangecanvas/scheme/scheme.py
- orangecanvas/scheme/widgetmanager.py
Sphinx 3.2.1 raises warnings for docs build (duplicated descriptions).
Fix sphinx warnings.
Mention docs in readme.
Bump sphinx to ~=3.2.1 in  docs/requirements-rtd.txt
> Documentation fixes

- orangecanvas/application/addons.py
Ref: gh-162
Only try pip fallback if conda fails with an error.
> addons: Try pip install only if conda fails with an error

- orangecanvas/document/suggestions.py
Fixes gh-164
Catch all errors from pickle.load call
> [FIX] suggestions: Catch all errors from pickle.load call

- orangecanvas/application/application.py
- orangecanvas/application/canvasmain.py
- orangecanvas/canvas/items/linkitem.py
- orangecanvas/canvas/items/nodeitem.py
- orangecanvas/canvas/scene.py
- orangecanvas/document/editlinksdialog.py
- orangecanvas/document/interactions.py
- orangecanvas/document/quickmenu.py
- orangecanvas/document/schemeedit.py
- orangecanvas/gui/itemmodels.py
- orangecanvas/registry/description.py
- orangecanvas/scheme/annotations.py
- orangecanvas/scheme/link.py
- orangecanvas/scheme/node.py
- orangecanvas/scheme/scheme.py
- orangecanvas/utils/__init__.py
- orangecanvas/utils/after_exit.py
- orangecanvas/utils/asyncutils.py
- orangecanvas/utils/pkgmeta.py
- orangecanvas/utils/shtools.py
Fix and improve various type hints.
> Fix and improve type hints

- orangecanvas/canvas/items/annotationitem.py
- orangecanvas/canvas/items/controlpoints.py
- orangecanvas/canvas/items/graphicstextitem.py
- orangecanvas/canvas/items/nodeitem.py
- orangecanvas/canvas/items/tests/test_nodeitem.py
- orangecanvas/document/schemeedit.py
- orangecanvas/document/tests/test_schemeedit.py
- orangecanvas/gui/utils.py
- orangecanvas/utils/qinvoke.py
- orangecanvas/utils/tests/test_qinvoke.py
Fixes gh-167
Implement inline node title editing
> [ENH] Edit node names inline

- orangecanvas/document/quickmenu.py
"one-hot" is now also matched by "onehot" and "one hot"
https://github.com/biolab/orange3/pull/5350
> quickmenu: Better sorting for keywords with -

- orangecanvas/application/canvasmain.py
- orangecanvas/application/outputview.py
- orangecanvas/application/tests/test_outputview.py
- orangecanvas/gui/utils.py
- orangecanvas/main.py
Refactor output view CanvasMainWindow.new_workflow_window, connect_output_stream, disconnect_output_stream and main stdout/stderr redirection setup.
> Refactor output view

- .github/workflows/run-tests-workflow.yml
Add Python 3.10 to test matrices
> [CI] Add Python 3.10 to test matrices

- orangecanvas/document/quickmenu.py
This reverts commit fbcb9ca6740bfc96e8f85f525f11102102c94f61.
In gh-138 the Sloppy button logic was removed. Although the categories buttons are not visible/enabled by default they can be enabled via settings and are more difficult to use without this.
> Revert "quickmenu: Remove sloppy button logic"

- orangecanvas/application/canvasmain.py
- orangecanvas/application/settings.py
- orangecanvas/canvas/items/nodeitem.py
- orangecanvas/canvas/scene.py
- orangecanvas/document/schemeedit.py
Closes:  gh-214
Add option to always open anchors on hover
> [ENH] Add option to always open anchors on hover

- .github/workflows/run-tests-workflow.yml
- orangecanvas/application/application.py
- orangecanvas/canvas/items/annotationitem.py
- orangecanvas/canvas/items/graphicstextitem.py
- orangecanvas/canvas/scene.py
- orangecanvas/canvas/view.py
- orangecanvas/document/editlinksdialog.py
- orangecanvas/document/quickmenu.py
- orangecanvas/document/schemeedit.py
- orangecanvas/document/tests/test_schemeedit.py
- orangecanvas/gui/textlabel.py
- orangecanvas/gui/toolbox.py
- orangecanvas/gui/toolgrid.py
- orangecanvas/gui/utils.py
- orangecanvas/registry/qt.py
- orangecanvas/scheme/events.py
- orangecanvas/utils/__init__.py
- orangecanvas/utils/overlay.py
- setup.py
> [ENH] Add support for PyQt6

- orangecanvas/document/interactions.py
- orangecanvas/scheme/scheme.py
Fixes: https://github.com/biolab/orange3/issues/5984
Discount explicit links when determining whether to replace an existing link.
> scheme: Further reduce proposed explicit link weights

- orangecanvas/scheme/signalmanager.py
- orangecanvas/scheme/tests/test_signalmanager.py
Fixes https://github.com/biolab/orange-canvas-core/issues/235
Dispatch `Signal.New` in `send` when link is disabled.
Similar was done before in 0e0f69354cec8bba7156c433b3ff13a20f666cbd for adding a new link in disabled state.
> [FIX] signalmanager: Dispatch `Signal.New` in `send` when link is disabled

- orangecanvas/gui/splashscreen.py
Fixes https://github.com/biolab/orange3/issues/6169
Use smooth pixmap transform
> splashscreen: Use smooth pixmap transform

- orangecanvas/application/canvasmain.py
- orangecanvas/gui/windowlistmanager.py
- orangecanvas/scheme/tests/test_widgetmanager.py
- orangecanvas/scheme/widgetmanager.py
- orangecanvas/utils/qinvoke.py
- orangecanvas/utils/tests/test_qinvoke.py
- setup.py
Ref: https://github.com/biolab/orange3/issues/6187
Add all open windows list to "Window" menu in the canvas.
For testing you will also need https://github.com/biolab/orange-widget-base/pull/220
> [ENH] Add all open windows list to "Window" menu

- orangecanvas/document/usagestatistics.py
Fixes https://github.com/biolab/orange3/issues/6290
Handle errors in usage statistics update
> [FIX] usagestatistics: Handle errors in usage statistics update

- .github/workflows/run-tests-workflow.yml
codecov on pypi is no longer available
Use codecov-action
> [MNT] CI: Use codecov-action

- .github/workflows/run-tests-workflow.yml
PyQt6 6.5 LTS has been released.
Add PyQt6 6.5 to test CI matrix.
> [MNT] CI: Add PyQt6 6.5 to test matrix

- orangecanvas/application/utils/addons.py
- setup.py
Fixes https://github.com/biolab/orange-canvas-core/issues/274
Replace use of cachecontrol with requests-cache
> addons: Replace use of cachecontrol with requests-cache

- orangecanvas/config.py
- orangecanvas/utils/pkgmeta.py
Distutils stdlib is [deprecated](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated)
Remove import and use of distutils
> Remove use of distutils

- orangecanvas/config.py
- setup.py
Ref: https://github.com/biolab/orange3/issues/6522
* config: Replace and fix use of pkg_resources.parse_version
> [FIX] config: Replace and fix use of pkg_resources.parse_version

- orangecanvas/document/interactions.py
> Drop Handler: Add a title to popup for widget selection

- .github/workflows/run-tests-workflow.yml
Add Python 3.13 and Qt 6.7 to test matrix
> [CI] Add Python 3.13 and Qt 6.7 

- orangecanvas/application/canvasmain.py
- orangecanvas/config.py
Ref: https://github.com/biolab/orange3/issues/6987#issuecomment-2750707248
Show help in external browser by default
> Show help in external browser by default
